server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
      prefer-ip-address: true
ribbon:
  eureka:
   enabled: false
visits-service:
  ribbon:
    listOfServers: visits-service:8082
customers-service:
  ribbon:
    listOfServers: customers-service:8081
vets-service:
  ribbon:
    listOfServers: vets-service:8083
api-gateway:
  ribbon:
    listOfServers: api-gateway:8080