server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
      hostname: "admin-server"
