spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8082
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
      prefer-ip-address: true
ribbon:
  eureka:
   enabled: false
visits-service:
  ribbon:
    listOfServers: visits-service:8083
customers-service:
  ribbon:
    listOfServers: customers-service:8083
vets-service:
  ribbon:
    listOfServers: vets-service:8083
api-gateway:
  ribbon:
    listOfServers: api-gateway:8080